Data access
Svetlaanaa/DictionaryProject pull request #3
Opened 2024-03-22 23:30 UTC by Svetlaanaa

2024-03-23 14:53 UTC, KorobetskayaAA requested changes
Проверьте .gitignore и уберите .class-файлы. В таком случае можно использовать amend коммита, чтобы исправить ошибку. Но на сервер GitHub исправление уйдет как отдельный коммит.

2024-03-23 14:53 UTC, KorobetskayaAA commented on src/test/java/ru/teamscore/dictionary/DefinitionTest.java
> +//class DefinitionTest {
Почему закомментировано?

2024-03-23 14:53 UTC, KorobetskayaAA commented on target/classes/ru/teamscore/dictionary/Definition.class
Папка target не должна коммититься! И вообще файлы .class. Проверьте .gitignore.

2024-03-24 13:36 UTC, Svetlaanaa commented on src/test/java/ru/teamscore/dictionary/DefinitionTest.java
> +//class DefinitionTest {
Я перенесла все методы из Definition в другой класс, поэтому DefinitionTest стал бесполезен. Теперь я его удалила совсем

2024-03-24 13:36 UTC, Svetlaanaa commented on target/classes/ru/teamscore/dictionary/Definition.class
Исправила

2024-03-24 15:23 UTC, KorobetskayaAA approved these changes
Принято.

2024-03-24 15:23 UTC, merged